### ISSUE TITLE
TLDs Missing

### ISSUE THREAD

**Issue by OmarHasan16** [centralnicgroup-opensource/rtldev-middleware-blesta#196]
Please install Blesta and setup cnr
But TLDs  missing

**Comment by KaiSchwarz-cnic** [comment]
@OmarHasan16 

Is your account at CNR already activated? Did you activate the TLDs you want to offer in your account at CNR (via CNR Web Interface)? That are the common problems we noticed at least around customers when getting started with CNR.

**Comment by OmarHasan16** [comment]
Thanks for information 👍. Please update documents how to active LTDs via web.yes I added LTDs via reseller panel. Still I have to do anything in my panel? I'm only support agent my comp

**Comment by AsifNawaz-cnic** [comment]
Hi @OmarHasan16,

To activate TLDs in the CentralNic Reseller Panel, navigate to CentralNic Reseller Panel > Domains > Domain Prices > Activate the TLD(s). If you cannot find your desired TLD, please contact our CentralNic Reseller [sales team](https://supportcentralnicreseller.com) for assistance with TLD activation.

Please refer to the attached screenshot for reference.
![image](https://github.com/user-attachments/assets/5b4be6aa-5625-4f3e-81d4-905371497073)

To import TLDs into Blesta, navigate to Blesta Admin Panel > Packages > Domain Options > Import TLDs > Module > CentralNic Reseller. Select the desired TLD(s) and click the "Import" button.

Please refer to the attached screenshot for reference.
![image](https://github.com/user-attachments/assets/24b58604-8932-4368-847d-acd6e3908d85)
